### ISSUE TITLE
Korla light changes when icon cache is made

### ISSUE THREAD

**Issue by freefreeno** [bikass/korla#10] opened 2019-02-16 16:33 UTC
When the I add the korla light icon theme it states that I need to generate a icon cache and when I do so it reverts to the gnome icons so something is up with the light version.

**Comment by bikass** [comment] 2019-02-16 16:36
Checked on Xubuntu there is warning about cache, but works. However there is problem with white panel some icons still white, same on budgie but different icons. I have no idea how to make it work (this is Panel and Action icons, but if you check them in text editor, they are correct). I will remove this light theme in next release.

**Comment by Digitalone1** [comment] 2019-02-17 10:37
> Checked on Xubuntu there is warning about cache, but works. However there is problem with white panel some icons still white, same on budgie but different icons. I have no idea how to make it work (this is Panel and Action icons, but if you check them in text editor, they are correct). I will remove this light theme in next release.

Warning about cache is because korla-light folder does not have icon-theme.cache file. You should add it, but do not copy it from korla folder, there should be a way to generate it on its own.

I think index.theme is wrong too. Maybe you need to specify folders like in the original korla index.them and add korla on top of inherits:
`Inherits=korla,breeze,gnome,hicolor`

Please do not remove it, fix it, maybe you can give a read to this: https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout

Unfortunately I don't have time in these days otherwise I would give a look.

**Comment by bikass** [comment] 2019-02-17 12:43
Hi,
Thanks, for looking into that. Looks like I'm going to need your help :) No rush - someday when you have time.
I tried to create cache separately, looks like working.
but there are issues like that, when panel is light some icons doesn't change to dark:
![screenshot from 2019-02-17 14 06 33](https://user-images.githubusercontent.com/8824269/52912840-e2662c80-32bf-11e9-8bf5-5b7e40d5d767.png)

Also I'm having hard time with "panel" icons. All icons like "actions","panel","status" - are 16x16.But "panel" icons just appear a lot bigger, but if I replace with 22x22 then size is correct (Wireless indicator):
![screenshot from 2019-02-17 14 10 04](https://user-images.githubusercontent.com/8824269/52912927-e2b2f780-32c0-11e9-9d20-64b50c8411e4.png)

I think index file need some improvements. Maybe all folder structure needs to be changed in order to work properly. 
I  think, that I'm already reached limits of my competence :)

**Comment by Digitalone1** [comment] 2019-02-17 21:04
Try to copy korla index theme file in korla-light folder and just modify theme name and add korla on top of inherits.

If icons won't show, maybe light ones have another name. I can't reproduce on my system, plasma themes do not allow to change icons on panels. 

Regarding index them file structure, I'll investigate when I have time.

**Comment by bikass** [comment] 2019-02-18 07:58
I remade korla-light with index from korla, and created symlinks to other folder. Now seems like cache is working

**Comment by freefreeno** [comment] 2019-02-19 03:16
I know the light version is being worked on so I reinstalled and you are correct about the cache file doesn't show to be missing anymore but in Arch xfce if you apply white theme the whisker menu completely leaves panel as well as mostly every other icon from panel in xfce. I am not sure about any others because I had to hurry and change it back to regular korla. I guess I should have kept my mouth shut about light version. lol .   I am trying to learn how to theme and I am at the beginning of a long journey with no experience so i can do is give feedback or I would be glad to help because I use the icons right now. I say make all panel icons white in dark version so that half the panel icons arent white and the others colored. So in other words anything you add to the panel should be a white icon on a dark theme and black or some dark color on the light version.

**Comment by bikass** [comment] 2019-02-19 14:58
Light theme's symlinks were broken. Should work now.
If you want to  help. You could look for wrong icons and find their names in some other themes which works. Then post names somewhere here and I will make them :)

**Comment by Digitalone1** [comment] 2019-02-23 10:39
I'm glad you fixed, I've updated on the AUR.

But I think directories structures can be made better. korla-light should have same directories as korla (except actions) and korla on top of inherits.

In this way you could add specific icons in the other categories and missing ones are inherited from korla. That's the same mechanism when a breeze/gnome icon is shown in place of a missing korla one. I have time now, so I'll make some tests and let you know.

**Comment by bikass** [comment] 2019-02-23 11:08
But this is exactly what I did :) Same folders in light theme, but all are symlinks to main theme except actions.

**Comment by Digitalone1** [comment] 2019-02-23 11:24
> But this is exactly what I did :) Same folders in light theme, but all are symlinks to main theme except actions.

No, I mean empty folders, not symlinks, I'm testing it and will let you know if it works. 

Anyway, looking into theme files, I noticed that Status category is missing. This category is used for system tray in Plasma. Maybe that's the reason panel icons were not working on my system. I'm doing some copying from Breeze theme file....

**Comment by Digitalone1** [comment] 2019-02-23 15:03
I was right, empty directories solution works. Korla-light shows icons inherited from Korla without symlinks, but unfortunately I had to revert to 0.8.5 version which I had in cache because some icons in last release are corrupted. I can't see emblems for locked or shared directores.

![screenshot_20190223_155540](https://user-images.githubusercontent.com/25790525/53288049-48e9bf80-3784-11e9-91b2-c769d69956cc.png)

If I clone git repository and browse emblem directory, some icons are not showed correctly.

**Comment by bikass** [comment] 2019-02-23 15:37
Yes some svg had image layers in emblems. Fixed. Should be fine now. 
And these empty folders, are they working with cache? What advantage over symlinks?

**Comment by Digitalone1** [comment] 2019-02-23 15:49
That's weird because I can't see them in the desktop, neither in Gwenview, but if I open with Chromium they're rendered properly. I'm going to clone the last git and checking...

Empty folders were working to me, I assume no issues with the cache. Advantage is that in the future you can add specific light icons without having to symlink all others in the same folder.

These are the headers of the index themes:

> [Icon Theme]
> Name=Korla
> Comment=Dark icon theme for Linux desktops. Mix of the following icon sets: La_Capitaine, MacOS11, Papirus.
> Inherits=breeze,gnome,hicolor

> [Icon Theme]
> Name=Korla Light
> Comment=Light icon theme for Linux desktops. Mix of the following icon sets: La_Capitaine, MacOS11, Papirus.
> Inherits=korla,breeze,gnome,hicolor

**Comment by Digitalone1** [comment] 2019-02-23 15:51
Just did a quick check, I can see all icons in emblems now.

**Comment by bikass** [comment] 2019-02-23 15:59
Ok, I assume those changes are good :) . Will you make a commit then?

**Comment by Digitalone1** [comment] 2019-02-23 16:00
In the next hour I think.

**Comment by Digitalone1** [comment] 2019-02-23 16:40
Did the commit, but I didn't consider that github won't save empty directory. -_-

Can you revert to your last commit?

**Comment by Digitalone1** [comment] 2019-02-23 16:42
Well, in this case it's better to stay with symlinks and If in the future you have to add specific light icons on other folders, you can add them and the others will be inherited by primary korla theme.

**Comment by Digitalone1** [comment] 2019-02-23 16:44
Or maybe we can do [this](https://davidwalsh.name/git-empty-directory). You choose.

**Comment by bikass** [comment] 2019-02-23 16:53
Reverted to previous commit. 
Lets leave with symlinks. Works at the moment and less headache.

**Comment by Digitalone1** [comment] 2019-02-23 16:58
Okay, I commited only index.theme files, addes status category which was missing. Did you resolve the issue with icon size in the panel?

**Comment by bikass** [comment] 2019-02-23 17:46
Thanks!
No, I didn't resolve panel stuff. Icon size is ok if I uses 22x22 icons. Just don't understand why icons are bigger when I put 16x16 icons. But would be nice to resolve this light and dark icon issue in panel. Icons are good, but don't understand why they are not changing into dark...

**Comment by Digitalone1** [comment] 2019-02-23 18:42
How you change size? Inside the svg text?

Maybe it's a dumb question, but did you check name compatibility? 

Some icons shows and others not? Unfortunately I can't test this on Plasma.

**Closed** 2019-03-10 10:33 UTC
